package seoft.co.kr.launcherq.ui.arrange

import android.content.Intent
import seoft.co.kr.launcherq.data.model.ExpertOption

/**
 * use result property to QuickApp when saving
 * use name property to setting view when loading
 */
class ExpertOptionModels {

    val actionDefault = Intent.ACTION_DEFAULT
    val flagDefault = Intent.FLAG_ACTIVITY_NEW_TASK
    val categoryDefault = Intent.CATEGORY_DEFAULT

    val actions = arrayListOf(
        ExpertOption("ACTION_DEFAULT", actionDefault),
        ExpertOption("ACTION_AIRPLANE_MODE_CHANGED","android.intent.action.AIRPLANE_MODE"),
        ExpertOption("ACTION_ALL_APPS","android.intent.action.ALL_APPS"),
        ExpertOption("ACTION_ANSWER","android.intent.action.ANSWER"),
        ExpertOption("ACTION_APPLICATION_PREFERENCES","android.intent.action.APPLICATION_PREFERENCES"),
        ExpertOption("ACTION_APPLICATION_RESTRICTIONS_CHANGED","android.intent.action.APPLICATION_RESTRICTIONS_CHANGED"),
        ExpertOption("ACTION_APP_ERROR","android.intent.action.APP_ERROR"),
        ExpertOption("ACTION_ASSIST","android.intent.action.ASSIST"),
        ExpertOption("ACTION_ATTACH_DATA","android.intent.action.ATTACH_DATA"),
        ExpertOption("ACTION_BATTERY_CHANGED","android.intent.action.BATTERY_CHANGED"),
        ExpertOption("ACTION_BATTERY_LOW","android.intent.action.BATTERY_LOW"),
        ExpertOption("ACTION_BATTERY_OKAY","android.intent.action.BATTERY_OKAY"),
        ExpertOption("ACTION_BOOT_COMPLETED","android.intent.action.BOOT_COMPLETED"),
        ExpertOption("ACTION_BUG_REPORT","android.intent.action.BUG_REPORT"),
        ExpertOption("ACTION_CALL","android.intent.action.CALL"),
        ExpertOption("ACTION_CALL_BUTTON","android.intent.action.CALL_BUTTON"),
        ExpertOption("ACTION_CAMERA_BUTTON","android.intent.action.CAMERA_BUTTON"),
        ExpertOption("ACTION_CARRIER_SETUP","android.intent.action.CARRIER_SETUP"),
        ExpertOption("ACTION_CHOOSER","android.intent.action.CHOOSER"),
        ExpertOption("ACTION_CLOSE_SYSTEM_DIALOGS","android.intent.action.CLOSE_SYSTEM_DIALOGS"),
        ExpertOption("ACTION_CONFIGURATION_CHANGED","android.intent.action.CONFIGURATION_CHANGED"),
        ExpertOption("ACTION_CREATE_DOCUMENT","android.intent.action.CREATE_DOCUMENT"),
        ExpertOption("ACTION_CREATE_SHORTCUT","android.intent.action.CREATE_SHORTCUT"),
        ExpertOption("ACTION_DATE_CHANGED","android.intent.action.DATE_CHANGED"),
        ExpertOption("ACTION_DEFAULT","android.intent.action.VIEW"),
        ExpertOption("ACTION_DELETE","android.intent.action.DELETE"),
        ExpertOption("ACTION_DEVICE_STORAGE_LOW","android.intent.action.DEVICE_STORAGE_LOW"),
        ExpertOption("ACTION_DEVICE_STORAGE_OK","android.intent.action.DEVICE_STORAGE_OK"),
        ExpertOption("ACTION_DIAL","android.intent.action.DIAL"),
        ExpertOption("ACTION_DOCK_EVENT","android.intent.action.DOCK_EVENT"),
        ExpertOption("ACTION_DREAMING_STARTED","android.intent.action.DREAMING_STARTED"),
        ExpertOption("ACTION_DREAMING_STOPPED","android.intent.action.DREAMING_STOPPED"),
        ExpertOption("ACTION_EDIT","android.intent.action.EDIT"),
        ExpertOption("ACTION_EXTERNAL_APPLICATIONS_AVAILABLE","android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE"),
        ExpertOption("ACTION_EXTERNAL_APPLICATIONS_UNAVAILABLE","android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE"),
        ExpertOption("ACTION_FACTORY_TEST","android.intent.action.FACTORY_TEST"),
        ExpertOption("ACTION_GET_CONTENT","android.intent.action.GET_CONTENT"),
        ExpertOption("ACTION_GET_RESTRICTION_ENTRIES","android.intent.action.GET_RESTRICTION_ENTRIES"),
        ExpertOption("ACTION_GTALK_SERVICE_CONNECTED","android.intent.action.GTALK_CONNECTED"),
        ExpertOption("ACTION_GTALK_SERVICE_DISCONNECTED","android.intent.action.GTALK_DISCONNECTED"),
        ExpertOption("ACTION_HEADSET_PLUG","android.intent.action.HEADSET_PLUG"),
        ExpertOption("ACTION_INPUT_METHOD_CHANGED","android.intent.action.INPUT_METHOD_CHANGED"),
        ExpertOption("ACTION_INSERT","android.intent.action.INSERT"),
        ExpertOption("ACTION_INSERT_OR_EDIT","android.intent.action.INSERT_OR_EDIT"),
        ExpertOption("ACTION_INSTALL_FAILURE","android.intent.action.INSTALL_FAILURE"),
        ExpertOption("ACTION_INSTALL_PACKAGE","android.intent.action.INSTALL_PACKAGE"),
        ExpertOption("ACTION_LOCALE_CHANGED","android.intent.action.LOCALE_CHANGED"),
        ExpertOption("ACTION_LOCKED_BOOT_COMPLETED","android.intent.action.LOCKED_BOOT_COMPLETED"),
        ExpertOption("ACTION_MAIN","android.intent.action.MAIN"),
        ExpertOption("ACTION_MANAGED_PROFILE_ADDED","android.intent.action.MANAGED_PROFILE_ADDED"),
        ExpertOption("ACTION_MANAGED_PROFILE_AVAILABLE","android.intent.action.MANAGED_PROFILE_AVAILABLE"),
        ExpertOption("ACTION_MANAGED_PROFILE_REMOVED","android.intent.action.MANAGED_PROFILE_REMOVED"),
        ExpertOption("ACTION_MANAGED_PROFILE_UNAVAILABLE","android.intent.action.MANAGED_PROFILE_UNAVAILABLE"),
        ExpertOption("ACTION_MANAGED_PROFILE_UNLOCKED","android.intent.action.MANAGED_PROFILE_UNLOCKED"),
        ExpertOption("ACTION_MANAGE_NETWORK_USAGE","android.intent.action.MANAGE_NETWORK_USAGE"),
        ExpertOption("ACTION_MANAGE_PACKAGE_STORAGE","android.intent.action.MANAGE_PACKAGE_STORAGE"),
        ExpertOption("ACTION_MEDIA_BAD_REMOVAL","android.intent.action.MEDIA_BAD_REMOVAL"),
        ExpertOption("ACTION_MEDIA_BUTTON","android.intent.action.MEDIA_BUTTON"),
        ExpertOption("ACTION_MEDIA_CHECKING","android.intent.action.MEDIA_CHECKING"),
        ExpertOption("ACTION_MEDIA_EJECT","android.intent.action.MEDIA_EJECT"),
        ExpertOption("ACTION_MEDIA_MOUNTED","android.intent.action.MEDIA_MOUNTED"),
        ExpertOption("ACTION_MEDIA_NOFS","android.intent.action.MEDIA_NOFS"),
        ExpertOption("ACTION_MEDIA_REMOVED","android.intent.action.MEDIA_REMOVED"),
        ExpertOption("ACTION_MEDIA_SCANNER_FINISHED","android.intent.action.MEDIA_SCANNER_FINISHED"),
        ExpertOption("ACTION_MEDIA_SCANNER_SCAN_FILE","android.intent.action.MEDIA_SCANNER_SCAN_FILE"),
        ExpertOption("ACTION_MEDIA_SCANNER_STARTED","android.intent.action.MEDIA_SCANNER_STARTED"),
        ExpertOption("ACTION_MEDIA_SHARED","android.intent.action.MEDIA_SHARED"),
        ExpertOption("ACTION_MEDIA_UNMOUNTABLE","android.intent.action.MEDIA_UNMOUNTABLE"),
        ExpertOption("ACTION_MEDIA_UNMOUNTED","android.intent.action.MEDIA_UNMOUNTED"),
        ExpertOption("ACTION_MY_PACKAGE_REPLACED","android.intent.action.MY_PACKAGE_REPLACED"),
        ExpertOption("ACTION_MY_PACKAGE_SUSPENDED","android.intent.action.MY_PACKAGE_SUSPENDED"),
        ExpertOption("ACTION_MY_PACKAGE_UNSUSPENDED","android.intent.action.MY_PACKAGE_UNSUSPENDED"),
        ExpertOption("ACTION_NEW_OUTGOING_CALL","android.intent.action.NEW_OUTGOING_CALL"),
        ExpertOption("ACTION_OPEN_DOCUMENT","android.intent.action.OPEN_DOCUMENT"),
        ExpertOption("ACTION_OPEN_DOCUMENT_TREE","android.intent.action.OPEN_DOCUMENT_TREE"),
        ExpertOption("ACTION_PACKAGES_SUSPENDED","android.intent.action.PACKAGES_SUSPENDED"),
        ExpertOption("ACTION_PACKAGES_UNSUSPENDED","android.intent.action.PACKAGES_UNSUSPENDED"),
        ExpertOption("ACTION_PACKAGE_ADDED","android.intent.action.PACKAGE_ADDED"),
        ExpertOption("ACTION_PACKAGE_CHANGED","android.intent.action.PACKAGE_CHANGED"),
        ExpertOption("ACTION_PACKAGE_DATA_CLEARED","android.intent.action.PACKAGE_DATA_CLEARED"),
        ExpertOption("ACTION_PACKAGE_FIRST_LAUNCH","android.intent.action.PACKAGE_FIRST_LAUNCH"),
        ExpertOption("ACTION_PACKAGE_FULLY_REMOVED","android.intent.action.PACKAGE_FULLY_REMOVED"),
        ExpertOption("ACTION_PACKAGE_INSTALL","android.intent.action.PACKAGE_INSTALL"),
        ExpertOption("ACTION_PACKAGE_NEEDS_VERIFICATION","android.intent.action.PACKAGE_NEEDS_VERIFICATION"),
        ExpertOption("ACTION_PACKAGE_REMOVED","android.intent.action.PACKAGE_REMOVED"),
        ExpertOption("ACTION_PACKAGE_REPLACED","android.intent.action.PACKAGE_REPLACED"),
        ExpertOption("ACTION_PACKAGE_RESTARTED","android.intent.action.PACKAGE_RESTARTED"),
        ExpertOption("ACTION_PACKAGE_VERIFIED","android.intent.action.PACKAGE_VERIFIED"),
        ExpertOption("ACTION_PASTE","android.intent.action.PASTE"),
        ExpertOption("ACTION_PICK","android.intent.action.PICK"),
        ExpertOption("ACTION_PICK_ACTIVITY","android.intent.action.PICK_ACTIVITY"),
        ExpertOption("ACTION_POWER_CONNECTED","android.intent.action.ACTION_POWER_CONNECTED"),
        ExpertOption("ACTION_POWER_DISCONNECTED","android.intent.action.ACTION_POWER_DISCONNECTED"),
        ExpertOption("ACTION_POWER_USAGE_SUMMARY","android.intent.action.POWER_USAGE_SUMMARY"),
        ExpertOption("ACTION_PROCESS_TEXT","android.intent.action.PROCESS_TEXT"),
        ExpertOption("ACTION_PROVIDER_CHANGED","android.intent.action.PROVIDER_CHANGED"),
        ExpertOption("ACTION_QUICK_CLOCK","android.intent.action.QUICK_CLOCK"),
        ExpertOption("ACTION_QUICK_VIEW","android.intent.action.QUICK_VIEW"),
        ExpertOption("ACTION_REBOOT","android.intent.action.REBOOT"),
        ExpertOption("ACTION_RUN","android.intent.action.RUN"),
        ExpertOption("ACTION_SCREEN_OFF","android.intent.action.SCREEN_OFF"),
        ExpertOption("ACTION_SCREEN_ON","android.intent.action.SCREEN_ON"),
        ExpertOption("ACTION_SEARCH","android.intent.action.SEARCH"),
        ExpertOption("ACTION_SEARCH_LONG_PRESS","android.intent.action.SEARCH_LONG_PRESS"),
        ExpertOption("ACTION_SEND","android.intent.action.SEND"),
        ExpertOption("ACTION_SENDTO","android.intent.action.SENDTO"),
        ExpertOption("ACTION_SEND_MULTIPLE","android.intent.action.SEND_MULTIPLE"),
        ExpertOption("ACTION_SET_WALLPAPER","android.intent.action.SET_WALLPAPER"),
        ExpertOption("ACTION_SHOW_APP_INFO","android.intent.action.SHOW_APP_INFO"),
        ExpertOption("ACTION_SHUTDOWN","android.intent.action.ACTION_SHUTDOWN"),
        ExpertOption("ACTION_SYNC","android.intent.action.SYNC"),
        ExpertOption("ACTION_SYSTEM_TUTORIAL","android.intent.action.SYSTEM_TUTORIAL"),
        ExpertOption("ACTION_TIMEZONE_CHANGED","android.intent.action.TIMEZONE_CHANGED"),
        ExpertOption("ACTION_TIME_CHANGED","android.intent.action.TIME_SET"),
        ExpertOption("ACTION_TIME_TICK","android.intent.action.TIME_TICK"),
        ExpertOption("ACTION_UID_REMOVED","android.intent.action.UID_REMOVED"),
        ExpertOption("ACTION_UMS_CONNECTED","android.intent.action.UMS_CONNECTED"),
        ExpertOption("ACTION_UMS_DISCONNECTED","android.intent.action.UMS_DISCONNECTED"),
        ExpertOption("ACTION_UNINSTALL_PACKAGE","android.intent.action.UNINSTALL_PACKAGE"),
        ExpertOption("ACTION_USER_BACKGROUND","android.intent.action.USER_BACKGROUND"),
        ExpertOption("ACTION_USER_FOREGROUND","android.intent.action.USER_FOREGROUND"),
        ExpertOption("ACTION_USER_INITIALIZE","android.intent.action.USER_INITIALIZE"),
        ExpertOption("ACTION_USER_PRESENT","android.intent.action.USER_PRESENT"),
        ExpertOption("ACTION_USER_UNLOCKED","android.intent.action.USER_UNLOCKED"),
        ExpertOption("ACTION_VIEW","android.intent.action.VIEW"),
        ExpertOption("ACTION_VOICE_COMMAND","android.intent.action.VOICE_COMMAND")
    )


    val categorys = arrayListOf(
        ExpertOption("CLEAR",""),
        ExpertOption("CATEGORY_ALTERNATIVE","android.intent.category.ALTERNATIVE"),
        ExpertOption("CATEGORY_APP_BROWSER","android.intent.category.APP_BROWSER"),
        ExpertOption("CATEGORY_APP_CALCULATOR","android.intent.category.APP_CALCULATOR"),
        ExpertOption("CATEGORY_APP_CALENDAR","android.intent.category.APP_CALENDAR"),
        ExpertOption("CATEGORY_APP_CONTACTS","android.intent.category.APP_CONTACTS"),
        ExpertOption("CATEGORY_APP_EMAIL","android.intent.category.APP_EMAIL"),
        ExpertOption("CATEGORY_APP_GALLERY","android.intent.category.APP_GALLERY"),
        ExpertOption("CATEGORY_APP_MAPS","android.intent.category.APP_MAPS"),
        ExpertOption("CATEGORY_APP_MARKET","android.intent.category.APP_MARKET"),
        ExpertOption("CATEGORY_APP_MESSAGING","android.intent.category.APP_MESSAGING"),
        ExpertOption("CATEGORY_APP_MUSIC","android.intent.category.APP_MUSIC"),
        ExpertOption("CATEGORY_BROWSABLE","android.intent.category.BROWSABLE"),
        ExpertOption("CATEGORY_CAR_DOCK","android.intent.category.CAR_DOCK"),
        ExpertOption("CATEGORY_CAR_MODE","android.intent.category.CAR_MODE"),
        ExpertOption("CATEGORY_DEFAULT","android.intent.category.DEFAULT"),
        ExpertOption("CATEGORY_DESK_DOCK","android.intent.category.DESK_DOCK"),
        ExpertOption("CATEGORY_DEVELOPMENT_PREFERENCE","android.intent.category.DEVELOPMENT_PREFERENCE"),
        ExpertOption("CATEGORY_EMBED","android.intent.category.EMBED"),
        ExpertOption("CATEGORY_FRAMEWORK_INSTRUMENTATION_TEST","android.intent.category.FRAMEWORK_INSTRUMENTATION_TEST"),
        ExpertOption("CATEGORY_HE_DESK_DOCK","android.intent.category.HE_DESK_DOCK"),
        ExpertOption("CATEGORY_HOME","android.intent.category.HOME"),
        ExpertOption("CATEGORY_INFO","android.intent.category.INFO"),
        ExpertOption("CATEGORY_LAUNCHER","android.intent.category.LAUNCHER"),
        ExpertOption("CATEGORY_LEANBACK_LAUNCHER","android.intent.category.LEANBACK_LAUNCHER"),
        ExpertOption("CATEGORY_LE_DESK_DOCK","android.intent.category.LE_DESK_DOCK"),
        ExpertOption("CATEGORY_MONKEY","android.intent.category.MONKEY"),
        ExpertOption("CATEGORY_OPENABLE","android.intent.category.OPENABLE"),
        ExpertOption("CATEGORY_PREFERENCE","android.intent.category.PREFERENCE"),
        ExpertOption("CATEGORY_SAMPLE_CODE","android.intent.category.SAMPLE_CODE"),
        ExpertOption("CATEGORY_SELECTED_ALTERNATIVE","android.intent.category.SELECTED_ALTERNATIVE"),
        ExpertOption("CATEGORY_TAB","android.intent.category.TAB"),
        ExpertOption("CATEGORY_TEST","android.intent.category.TEST"),
        ExpertOption("CATEGORY_TYPED_OPENABLE","android.intent.category.TYPED_OPENABLE"),
        ExpertOption("CATEGORY_UNIT_TEST","android.intent.category.UNIT_TEST"),
        ExpertOption("CATEGORY_VOICE","android.intent.category.VOICE"),
        ExpertOption("CATEGORY_VR_HOME","android.intent.category.VR_HOME")

        )

    val flags = mutableListOf(
        // add delete & clear from caller
        ExpertOption("FLAG_ACTIVITY_BROUGHT_TO_FRONT","4194304"),
        ExpertOption("FLAG_ACTIVITY_CLEAR_TASK","32768"),
        ExpertOption("FLAG_ACTIVITY_CLEAR_TOP","67108864"),
        ExpertOption("FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET","524288"),
        ExpertOption("FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS","8388608"),
        ExpertOption("FLAG_ACTIVITY_FORWARD_RESULT","33554432"),
        ExpertOption("FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY","1048576"),
        ExpertOption("FLAG_ACTIVITY_LAUNCH_ADJACENT","4096"),
        ExpertOption("FLAG_ACTIVITY_MATCH_EXTERNAL","2048"),
        ExpertOption("FLAG_ACTIVITY_MULTIPLE_TASK","134217728"),
        ExpertOption("FLAG_ACTIVITY_NEW_DOCUMENT","524288"),
        ExpertOption("FLAG_ACTIVITY_NEW_TASK","268435456"),
        ExpertOption("FLAG_ACTIVITY_NO_ANIMATION","65536"),
        ExpertOption("FLAG_ACTIVITY_NO_HISTORY","1073741824"),
        ExpertOption("FLAG_ACTIVITY_NO_USER_ACTION","262144"),
        ExpertOption("FLAG_ACTIVITY_PREVIOUS_IS_TOP","16777216"),
        ExpertOption("FLAG_ACTIVITY_REORDER_TO_FRONT","131072"),
        ExpertOption("FLAG_ACTIVITY_RESET_TASK_IF_NEEDED","2097152"),
        ExpertOption("FLAG_ACTIVITY_RETAIN_IN_RECENTS","8192"),
        ExpertOption("FLAG_ACTIVITY_SINGLE_TOP","536870912"),
        ExpertOption("FLAG_ACTIVITY_TASK_ON_HOME","16384"),
        ExpertOption("FLAG_DEBUG_LOG_RESOLUTION","8"),
        ExpertOption("FLAG_EXCLUDE_STOPPED_PACKAGES","16"),
        ExpertOption("FLAG_FROM_BACKGROUND","4"),
        ExpertOption("FLAG_GRANT_PERSISTABLE_URI_PERMISSION","64"),
        ExpertOption("FLAG_GRANT_PREFIX_URI_PERMISSION","128"),
        ExpertOption("FLAG_GRANT_READ_URI_PERMISSION","1"),
        ExpertOption("FLAG_GRANT_WRITE_URI_PERMISSION","2"),
        ExpertOption("FLAG_INCLUDE_STOPPED_PACKAGES","32"),
        ExpertOption("FLAG_RECEIVER_FOREGROUND","268435456"),
        ExpertOption("FLAG_RECEIVER_NO_ABORT","134217728"),
        ExpertOption("FLAG_RECEIVER_REGISTERED_ONLY","1073741824"),
        ExpertOption("FLAG_RECEIVER_REPLACE_PENDING","536870912"),
        ExpertOption("FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS","2097152")
        )









}