package seoft.co.kr.launcherq.ui

enum class MsgType {
    START_ACTIVITY ,
    FINISH_ACTIVITY,
    PICK_COLOR,
    OPEN_INPUT_DIALOG,
    UPDATE_APPS,
    SHOW_SETTING_DAILOG,
    CLEAR_SEARCH_EDIT_TEXT,
    SELECT_APP,
    SELECT_APP_IN_FOLDER,
    OPEN_FOLDER,
    PICK_TWO_STEP_ITEM,
//    REFRESH_SETTING,
}

